dictionary = {
    "Namaste": "Hello/Hi",
    "Dhanyavaad": "Thank you",
    "Kitaab": "Book",
    "Paani": "Water",
    "Dost": "Friend",
    "Ghar": "Home/House",
    "School": "School",
    "Khaana": "Food/Meal",
    "Chalo": "Let's go",
    "Prem": "Love",
    "Vidyalaya": "School",
    "Pustak": "Book",
    "Aaj": "Today",
    "Kal": "Tomorrow or Yesterday",
    "Subah": "Morning",
    "Shaam": "Evening",
    "Raat": "Night",
    "Safar": "Journey or Travel",
    "Parivaar": "Family",
    "Sundar": "Beautiful",
    "Tez": "Fast",
    "Mausam": "Weather",
    "Safed": "White",
    "Kala": "Black",
    "Lal": "Red",
    "Neela": "Blue",
    "Peela": "Yellow",
    "Hara": "Green",
    "Dukaan": "Shop or Store",
    "Bazaar": "Market",
    "Gaadi": "Car or Vehicle",
    "Chhat": "Roof",
    "Pankha": "Fan",
    "Darwaza": "Door",
    "Khidki": "Window",
    "Padhai": "Study",
    "Kaam": "Work or Job",
    "Saathi": "Companion",
    "Swagat": "Welcome",
    "Aasman": "Sky",
    "Zameen": "Land or Earth",
    "Ped": "Tree",
    "Phool": "Flower",
    "Samaan": "Goods or Things",
    "Khushi": "Happiness",
    "Dukh": "Sadness",
    "Mitra": "Friend",
    "Aankh": "Eye",
    "Haath": "Hand",
    "Pair": "Leg or Foot",
    "Munh": "Mouth",
    "Sir": "Head",
    "Dil": "Heart",
    "Awaaz": "Voice or Sound",
    "Sapna": "Dream",
    "Sach": "Truth",
    "Jhoot": "Lie"
}

word = input("Enter the word you want meaning of : ")
print( dictionary[word])